fospas/Space-Cats-14

- Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml
Агост может видеть должность и мш
**Медиа**
**Проверки**
**Изменения**
:cl:
- tweak: Агост может видеть должность и мш
> Агост может видеть должность и мш

- Content.Server/Administration/Commands/AdminWhoCommand.cs
В adminwho видно пропущенная строчка, что показывает скрытого админа.
**Медиа**
**Проверки**
**Изменения**
:cl:
- fix: В adminwho видно пропущенная строчка, что показывает скрытого админа.
> В adminwho видно пропущенная строчка, что показывает скрытого админа.

- Content.Server/Administration/Systems/BwoinkSystem.cs
- Content.Server/Chat/Managers/ChatManager.cs
Админ префикс для Ахелпа и АдминЧата.
:cl:
- tweak: Админ префикс для Ахелпа и АдминЧата.
> админ префикс для ахелпа/админ чата

- Content.Server/Corvax/ChatFilter/ChatSystem.cs
Смена текста на более "радостное"
:cl:
- tweak: Долой сюрикены.
> Подарок для набегаторов.

- Content.Client/Options/UI/EscapeMenu.xaml
- Content.Client/UserInterface/Systems/EscapeMenu/EscapeUIController.cs
- Content.Client/UserInterface/Systems/Ghost/Controls/Roles/GhostRolesWindow.xaml.cs
- Resources/Locale/en-US/escape-menu/ui/escape-menu.ftl
- Resources/Locale/ru-RU/backmen/playtime.ftl
- Resources/Locale/ru-RU/escape-menu/ui/escape-menu.ftl
Добавляем кнопку в меню, которая перевод в дискорд сервера. Сам сервер должен быть указан в CCVar заранее **InfoLinksDiscord**
:cl:
- add: кнопка в меню с переходом в Дискорд проекта.
> Add discord button in escape menu

- Resources/Prototypes/Roles/Jobs/Security/detective.yml
Небольшой фикс отсутствия какого либо бюджета у роли детектива. Тут не на что смотреть
> детектив - добавление зарплат и стартового счета

- Resources/Prototypes/_Backmen/game_presets.yml
Убран из голосование режим Крушение. В голосовании добавлены: Вампиры, культ, блоб.
:cl:
- remove: из голосования убран режим кораблекрушение
- tweak: добавлены в голосовании; вампиры, культ и блоб
> Убран из голосование режим Крушение. В голосовании добавлены: Вампиры, культ, блоб.

- Resources/Prototypes/Entities/Stations/base.yml
Убран огромный обломок который нагружал сервер.
:cl:
- remove: огромный обломок который не используется, так ещё и сервер нагружал.
> Убираем обломок который очень сильно нагружает. И не используется.

- Resources/Prototypes/Entities/Mobs/Player/silicon.yml
ИИ теперь может смотреть глазами боргов, и телепортироваться к ним для наблюдения.
:cl:
- add: ИИ может видеть зрениями боргов напрямую.
- add: ИИ может телепортироваться к боргам для зрения через панель.
> ИИ теперь может видить глазами боргов.

- Resources/Prototypes/Entities/Mobs/Player/silicon.yml
Reverts fospas/Space-Cats-14#46
> Revert "ИИ теперь может видить глазами боргов."

- Resources/Prototypes/_Backmen/Roles/Jobs/CentCom/cargotech.yml
- Resources/Prototypes/_Backmen/Roles/Jobs/CentCom/centcom_admiral.yml
- Resources/Prototypes/_Backmen/Roles/Jobs/CentCom/head_of_security.yml
- Resources/Prototypes/_Backmen/Roles/Jobs/CentCom/intern.yml
- Resources/Prototypes/_Backmen/Roles/Jobs/CentCom/operator.yml
- Resources/Prototypes/_Backmen/Roles/Jobs/CentCom/private_officer.yml
Понижение требуемого времени для открытие ролей ЦК.
:cl:
- tweak: Понижение требуемого времени для открытие ролей ЦК.
> понижение времени для ЦК

- Resources/Prototypes/Corvax/Entities/Mobs/Customization/Markings/cat_parts.yml
- Resources/Prototypes/Corvax/Entities/Mobs/Customization/Markings/fox_parts.yml
- Resources/Prototypes/Corvax/Entities/Mobs/Customization/Markings/human_hair.yml
- Resources/Prototypes/Corvax/Entities/Mobs/Customization/Markings/slime_cat_parts.yml
- Resources/Prototypes/Corvax/Entities/Mobs/Customization/Markings/slime_fox_parts.yml
- Resources/Prototypes/Corvax/Species/vulpkanin.yml
- Resources/Prototypes/Entities/Mobs/Customization/Markings/cat_parts.yml
Убираем ограничение на кастомизацию из-за спонсорки
:cl:
- remove: SponsorOnly убран.
> Убираем ограничение на кастомизацию.

- Resources/Prototypes/Objectives/thief.yml
**Цели по краже животных, когда достаточно просто их погладить, выглядят глупо и не целесообразно. Такие задачи явно не оправдывают себя, но занимают собой более интересные цели.**
_К тому же, я знатно подгорел, когда на карте Cluster не смог найти Morty, что привело к удалению всех связанных с животными краж._
~~У меня больше не горит~~
**Проверки**
🆑
- remove: Цели на кражу животных у вора.
> Убираем цели на животных у вора.

- Content.Client/Inventory/StrippableBoundUserInterface.cs
- Content.Client/Lobby/LobbyUIController.cs
- Resources/Locale/ru-RU/backmen/preferences/loadout-groups.ftl
- Resources/Prototypes/Loadouts/role_loadouts.yml
- Resources/Prototypes/_Backmen/Loadouts/Miscellaneous/clothingUnder.yml
- Resources/Prototypes/_Backmen/Loadouts/role_loadout.yml
* лодауты для нижней одежды
не всё, потому что много не нужного
* бригмед без трусов :skull:
* нужно починить только слои
низ отображается поверх верха, нужно ждать фикса самого слоя одежды в персонализации
* Update StrippableBoundUserInterface.cs
* Update LobbyUIController.cs
---------
**Медиа**
**Проверки**
**Изменения**
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!
> лодауты для нижней одежды (#709)

- Resources/Prototypes/_Backmen/Entities/Clothing/Under/pants.yml
- Resources/Prototypes/_Backmen/Entities/Clothing/Under/shirts.yml
- Resources/Prototypes/_Backmen/Entities/Clothing/Under/socks.yml
Приятный деликатес для Молей. Теперь можно есть своё же бельё. ~~Ну или чужое~~
:cl:
- add: Возможность за моль есть нижнее бельё.
> Теперь бельё может насытить моль, просто их съев.

- Resources/Prototypes/Catalog/Fills/Books/bookshelf.yml
- Resources/Prototypes/_Backmen/Entities/Objects/Misc/authorbooks.yml
Reverts fospas/Space-Cats-14#72
> Revert "remove book"

- Resources/Prototypes/_Backmen/Entities/Mobs/Player/stationai.yml
ИИ видит должность, МЩ, статус и здоровье. Как Синтов так и гуманоидов.
:cl:
- add: ИИ видит должность, МЩ, статус и здоровье. Как Синтов так и гуманоидов.
> ИИ может видить должности, статус и здоровье.

- Resources/Prototypes/Corvax/Maps/astra.yml
- Resources/Prototypes/Corvax/Maps/avrite.yml
- Resources/Prototypes/Corvax/Maps/delta.yml
- Resources/Prototypes/Corvax/Maps/frame.yml
- Resources/Prototypes/Corvax/Maps/gelta.yml
- Resources/Prototypes/Corvax/Maps/ishimura.yml
- Resources/Prototypes/Corvax/Maps/maus.yml
- Resources/Prototypes/Corvax/Maps/outpost.yml
- Resources/Prototypes/Corvax/Maps/paper.yml
- Resources/Prototypes/Corvax/Maps/pearl.yml
- Resources/Prototypes/Corvax/Maps/pilgrim.yml
- Resources/Prototypes/Corvax/Maps/terra.yml
- Resources/Prototypes/Maps/bagel.yml
- Resources/Prototypes/Maps/box.yml
- Resources/Prototypes/Maps/cluster.yml
- Resources/Prototypes/Maps/core.yml
- Resources/Prototypes/Maps/europa.yml
- Resources/Prototypes/Maps/fland.yml
- Resources/Prototypes/Maps/meta.yml
- Resources/Prototypes/Maps/oasis.yml
- Resources/Prototypes/Maps/omega.yml
- Resources/Prototypes/Maps/origin.yml
- Resources/Prototypes/Maps/saltern.yml
- Resources/Prototypes/Maps/train.yml
- Resources/Prototypes/_Backmen/Maps/backmen_aspid.yml
- Resources/Prototypes/_Backmen/Maps/backmen_kettle.yml
- Resources/Prototypes/_Backmen/Maps/no_madDelta.yml
На всех картах доступны БС дроны для работ.
:cl:
- add: На всех картах доступны БС дроны для работ.
> На всех станциях открыты БС дроны.

- Content.Client/Administration/UI/Bwoink/BwoinkControl.xaml.cs
- Content.Client/Administration/UI/CustomControls/PlayerListControl.xaml.cs
Исправляет сортировку в Ahelp
:cl:
- fix: Fixed Ahelp Sorting
> Fix aHelp menu sorting

- Resources/Prototypes/Entities/Mobs/Player/silicon.yml
Теперь у всех боргов есть фонарик.. Не знаю почему его не было. При этом у обычного drone он имеется.
**Проверки**
:cl:
- add: теперь у боргов есть осветительный прибор в виде фонарика
> Возвращаю боргам фонарики.

- Resources/Prototypes/_SpaceCats/Sponsor/Loadouts/Fredik21.yml
Обозначение перепутал. Теперь показывает и одевается корректно.
:cl:
- tweak: правильное отображение и спавн.
> fix sponsor

- Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
Фонарики на корпусы боргов.
:cl:
- fix: вернул боргам фонарики
> fix light borg add

- Resources/Prototypes/_SpaceCats/Sponsor/Loadouts/fospas.yml
Спонсорский лодаут для спонсора fospas
:cl:
- add: лодаут для спонсора
> add lodout sponsor fospas

- Resources/Prototypes/Entities/Stations/base.yml
Никому не нужный обломок который ещё и засирает всё гридами.
:cl:
- remove: убран обломок  borer
> remove lag borer

- Resources/Prototypes/Entities/Clothing/Head/hardsuit-helmets.yml
Теперь шлем отображается корректно на скафандре капитана.
:cl:
- fix: корректное отображение шлема капитана.
> fix cap hardsuit head

- Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Временная отключение экспедиции, до исправление с нагруженностью.
:cl:
- remove: экспедиционная консоль отключена
> disable SalvageExpedition

- Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
Теперь снова  починил фонарик, в этот раз нормально.
:cl:
- fix: фонарик теперь светит.
> fix light again

- Resources/Prototypes/Entities/Mobs/Player/dragon.yml
Поднимаем дракона. Теперь на него не работают флешки, радиация, стан и прочие мерзкие пакости.
:cl:
- tweak: дракон стал сильней, теперь он не боится радиации, травмат, флешки и урон по стамине.
> up space dragon

- Resources/Prototypes/_Backmen/Entities/Mobs/Species/shadowkin.yml
- Resources/Prototypes/_SpaceCats/Entities/Mobs/Species/base.yml
Сумеречники больше не задыхаются и не проигрывают *задыхается*
:cl:
- fix: сумеречники больше не проигрывают *задыхается*
> fix Shadowkin gasp

- Content.Server/Players/PlayTimeTracking/PlayTimeTrackingSystem.cs
Игрок не в deadmine не получал наигранное время на работы/должности. Теперь получает.
:cl:
- fix: теперь администратор в readmine получает наигранное время на отделы/работы. Ранее не получал.
> Теперь игрок в админе получает время на работах

- Resources/Prototypes/Entities/Structures/Windows/clockwork.yml
- Resources/Prototypes/Entities/Structures/Windows/mining.yml
- Resources/Prototypes/Entities/Structures/Windows/plasma.yml
- Resources/Prototypes/Entities/Structures/Windows/plastitanium.yml
- Resources/Prototypes/Entities/Structures/Windows/reinforced.yml
- Resources/Prototypes/Entities/Structures/Windows/rplasma.yml
- Resources/Prototypes/Entities/Structures/Windows/ruranium.yml
- Resources/Prototypes/Entities/Structures/Windows/uranium.yml
- Resources/Prototypes/Entities/Structures/Windows/window.yml
Reverts fospas/Space-Cats-14#151
> Revert "как я устал..."

- Resources/Prototypes/Entities/Structures/Windows/clockwork.yml
- Resources/Prototypes/Entities/Structures/Windows/mining.yml
- Resources/Prototypes/Entities/Structures/Windows/plasma.yml
- Resources/Prototypes/Entities/Structures/Windows/plastitanium.yml
- Resources/Prototypes/Entities/Structures/Windows/reinforced.yml
- Resources/Prototypes/Entities/Structures/Windows/rplasma.yml
- Resources/Prototypes/Entities/Structures/Windows/ruranium.yml
- Resources/Prototypes/Entities/Structures/Windows/uranium.yml
- Resources/Prototypes/Entities/Structures/Windows/window.yml
Reverts fospas/Space-Cats-14#153
> Revert "Revert "как я устал...""

- Resources/Prototypes/Entities/Structures/Windows/clockwork.yml
- Resources/Prototypes/Entities/Structures/Windows/mining.yml
- Resources/Prototypes/Entities/Structures/Windows/plasma.yml
- Resources/Prototypes/Entities/Structures/Windows/plastitanium.yml
- Resources/Prototypes/Entities/Structures/Windows/reinforced.yml
- Resources/Prototypes/Entities/Structures/Windows/rplasma.yml
- Resources/Prototypes/Entities/Structures/Windows/ruranium.yml
- Resources/Prototypes/Entities/Structures/Windows/uranium.yml
- Resources/Prototypes/Entities/Structures/Windows/window.yml
Лень пока исправлять ошибки связанные с этим. Починю позже.
:cl:
- remove: разрушенные окна после уничтожение окна больше не спавнятся.
> Вернуть обычные окна без разрушение.

- Resources/Prototypes/Entities/Structures/Lighting/base_lighting.yml
diff light
:cl:
- tweak: уменьшить свет от ламп
> light diff

- Resources/Maps/Backmen/backmen_aspid.yml
- Resources/Maps/atlas.yml
- Resources/Maps/bagel.yml
- Resources/Maps/core.yml
- Resources/Maps/corvax_ishimura.yml
- Resources/Maps/corvax_maus.yml
- Resources/Maps/corvax_paper.yml
- Resources/Maps/corvax_pearl.yml
- Resources/Maps/corvax_silly.yml
- Resources/Maps/europa.yml
- Resources/Maps/marathon.yml
- Resources/Maps/oasis.yml
- Resources/Maps/saltern.yml
- Resources/Maps/train.yml
Remove secret doors
**Медиа**
:cl:
- remove: скрытые двери убраны со всех карт
> Remove secret door

- Content.Server/Chat/Systems/ChatSystem.cs
Reverts fospas/Space-Cats-14#213
> Revert "add"

- Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
- Resources/Prototypes/Roles/Jobs/Command/captain.yml
- Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
- Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
- Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
- Resources/Prototypes/Roles/Jobs/Science/research_director.yml
- Resources/Prototypes/Roles/Jobs/Security/brigmedic.yml
- Resources/Prototypes/Roles/Jobs/Security/detective.yml
- Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
- Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
- Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
- Resources/Prototypes/Roles/Jobs/Security/warden.yml
- Resources/Prototypes/_Backmen/Roles/Jobs/CentCom/blueshield.yml
- Resources/Prototypes/_Backmen/Roles/Jobs/CentCom/cargotech.yml
- Resources/Prototypes/_Backmen/Roles/Jobs/CentCom/centcom_admiral.yml
- Resources/Prototypes/_Backmen/Roles/Jobs/CentCom/centcom_official.yml
- Resources/Prototypes/_Backmen/Roles/Jobs/CentCom/head_of_security.yml
- Resources/Prototypes/_Backmen/Roles/Jobs/CentCom/intern.yml
- Resources/Prototypes/_Backmen/Roles/Jobs/CentCom/operator.yml
- Resources/Prototypes/_Backmen/Roles/Jobs/CentCom/private_officer.yml
> add age 30

- Resources/Prototypes/_Backmen/Roles/Jobs/CentCom/blueshield.yml
Спидран по мелким фиксам и небольшим ребалансам, поехали!
- [✅] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [✅] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [❌] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [❌] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.
Переложил ножик ОСЩ с шеи на карман. Теперь плащики в лодаутах будут отображаться корректно
> перенос ножа в карман

- Resources/Prototypes/_Backmen/Entities/Objects/Weapons/Guns/Energy/hitscan.yml
Всё сказано в названии, говорить больше нечего
> ускорил заряд доминатора в 2 раза. Может, так он станет полезнее?

- Resources/Prototypes/_Backmen/Entities/Clothing/Eyes/glasses.yml
встроенный медхуд в ОСЩ очках.
> add OSH hud

- Resources/Prototypes/_Backmen/Entities/Objects/Weapons/Guns/Energy/hitscan.yml
Всё сказано в названии
-  Убрано веселье!
> теперь коллизия доминатора в сумках правильная

- Content.Server/EntityEffects/Effects/MakeSentient.cs
- Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Когнизин не работает на гуманоидов.
Вернул режимы экспедиции.
> Disable cognizine ghost roles for humanoids. and open survage

- Content.Server/Access/Systems/IdCardSystem.cs
- Content.Server/Access/Systems/PresetIdCardSystem.cs
- Content.Server/Radio/EntitySystems/RadioSystem.cs
- Content.Server/Station/Systems/StationSpawningSystem.cs
- Content.Shared/Access/Components/IdCardComponent.cs
- Content.Shared/Roles/JobPrototype.cs
- Resources/Locale/ru-RU/headset/headset-component.ftl
- Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
- Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
- Resources/Prototypes/Roles/Jobs/Command/captain.yml
- Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
- Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
- Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
- Resources/Prototypes/Roles/Jobs/Science/research_director.yml
- Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
- Resources/Prototypes/_Backmen/Roles/Jobs/CentCom/blueshield.yml
Reverts fospas/Space-Cats-14#323
> Revert "radio color jobs"

- Content.Client/Backmen/Standing/LayingDownSystem.cs
- Content.Client/Buckle/BuckleSystem.cs
- Content.Client/Input/ContentContexts.cs
- Content.Client/Options/UI/Tabs/KeyRebindTab.xaml.cs
- Content.Client/UserInterface/Systems/Ghost/Widgets/GhostGui.xaml.cs
- Content.IntegrationTests/Tests/Buckle/BuckleTest.cs
- Content.Server/Backmen/Ghost/GhostReJoinSystem.cs
- Content.Server/Backmen/Standing/LayingDownSystem.cs
- Content.Server/Ghost/GhostSystem.cs
- Content.Server/NPC/Systems/NPCCombatSystem.Ranged.cs
- Content.Shared/Backmen/CCVar/CCVars.cs
- Content.Shared/Backmen/Standing/LayingDownComponent.cs
- Content.Shared/Backmen/Standing/SharedLayingDownSystem.cs
- Content.Shared/Buckle/SharedBuckleSystem.Buckle.cs
- Content.Shared/Ghost/SharedGhostSystem.cs
- Content.Shared/Input/ContentKeyFunctions.cs
- Content.Shared/Standing/StandingStateComponent.cs
- Content.Shared/Standing/StandingStateSystem.cs
- Content.Shared/Stunnable/SharedStunSystem.cs
- Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs
- Resources/Locale/ru-RU/backmen/escape-menu/options-menu.ftl
- Resources/Locale/ru-RU/escape-menu/ui/options-menu.ftl
- Resources/Prototypes/Entities/Mobs/Species/base.yml
- Resources/keybinds.yml
> Upd upstream

- Content.Server/Backmen/Vampiric/BloodSuckerSystem.cs
- Content.Server/Backmen/Vampiric/Rule/BloodsuckerRuleComponent.cs
- add: Теперь все расы могут стать вампирами. Кроме слаймолюдей.
- tweak: Вампиры теперь получает в три раза больше очков при высасывании крови.
> Rebalance vamp

- Content.Shared/CCVar/CCVars.cs
Reverts fospas/Space-Cats-14#380
> Revert "0f screen shake"

- Resources/Prototypes/_Backmen/Entities/Clothing/OuterClothing/misc.yml
Добавлен кармашек в накидку на ведьм 2 на 3, как у стандартного лабараторного халата и тп
> Карман для накидки охотника на ведьм

- Content.Server/Chemistry/EntitySystems/HypospraySystem.cs
- Content.Server/Chemistry/EntitySystems/InjectorSystem.cs
- Content.Shared/_Cats/Clothing/Components/InjectableClothingComponent.cs
- Resources/Locale/ru-RU/_Cats/chemistry/components/hypospray-component.ftl
- Resources/Locale/ru-RU/_Cats/chemistry/components/injector-component.ftl
- Resources/Prototypes/Entities/Clothing/Head/base_clothinghead.yml
- Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml
add: Теперь в скафандры нельзя ничего инжектить Шприцами/Гипоспреями. Только при условии, если шлем скафандра не одет.
> protect injector hardsuit

- Content.Server/Access/Systems/IdCardSystem.cs
- Content.Server/Access/Systems/PresetIdCardSystem.cs
- Content.Server/Radio/EntitySystems/RadioSystem.cs
- Content.Server/Station/Systems/StationSpawningSystem.cs
- Content.Shared/Access/Components/IdCardComponent.cs
- Content.Shared/Roles/JobPrototype.cs
- Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
- Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
- Resources/Prototypes/Roles/Jobs/Command/captain.yml
- Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
- Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
- Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
- Resources/Prototypes/Roles/Jobs/Science/research_director.yml
- Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
- Resources/Prototypes/_Backmen/Roles/Jobs/CentCom/blueshield.yml
Reverts fospas/Space-Cats-14#572
> Revert "radio color"
